version: '3'
services:
    db:
        image: 'postgres:11'
        container_name: 'my_postgres'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres_docker_test
        ports:
            - '54320:5432'
        volumes:
            - ./my_dbdata/data:/var/lib/postgresql/data
            - ./my_dbdata/init:/docker-entrypoint-initdb.d
volumes:
    my_dbdata:
